name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - run: npm ci
      - run: npx nx affected --target=lint       --all --parallel=3
      - run: npx nx affected --target=type-check --all --parallel=3
      - run: npx nx affected --target=test       --all --parallel=3 --ci --code-coverage
      - run: npx nx affected --target=build      --all --parallel=3
